1: Import the Required Libraries

In [0]:
import pandas as pd

Step 2: Load the CSV Dataset

In [0]:
df = spark.table("workspace.default.sample_superstore").toPandas()

Step 3: Display the First 5 Rows

In [0]:
df.head()

   Row ID        Order ID  Order Date  ... Quantity Discount    Profit
0       1  CA-2016-152156  2016-11-08  ...        2     0.00   41.9136
1       2  CA-2016-152156  2016-11-08  ...        3     0.00  219.5820
2       3  CA-2016-138688  2016-06-12  ...        2     0.00    6.8714
3       4  US-2015-108966  2015-10-11  ...        5     0.45 -383.0310
4       5  US-2015-108966  2015-10-11  ...        2     0.20    2.5164

[5 rows x 21 columns]

Step 4: Display the Last 5 Rows

In [0]:
df.tail()

      Row ID        Order ID  Order Date  ... Quantity Discount   Profit
9989    9990  CA-2014-110422  2014-01-21  ...        3      0.2   4.1028
9990    9991  CA-2017-121258  2017-02-26  ...        2      0.0  15.6332
9991    9992  CA-2017-121258  2017-02-26  ...        2      0.2  19.3932
9992    9993  CA-2017-121258  2017-02-26  ...        4      0.0  13.3200
9993    9994  CA-2017-119914  2017-05-04  ...        2      0.0  72.9480

[5 rows x 21 columns]

Step 5: Display the Shape

In [0]:
df.shape

(9994, 23)

6.columns

In [0]:
print(df.columns)

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'total_amount', 'price'],
      dtype='object')

7. describe the table

In [0]:
df.describe()

            Row ID   Postal Code  ...  total_amount        price
count  9994.000000   9994.000000  ...   9994.000000  9994.000000
mean   4997.500000  55190.379428  ...    229.858001    60.919569
std    2885.163629  32063.693350  ...    623.245101   142.927440
min       1.000000   1040.000000  ...      0.444000     0.336000
25%    2499.250000  23223.000000  ...     17.280000     5.470000
50%    4997.500000  56430.500000  ...     54.490000    16.270000
75%    7495.750000  90008.000000  ...    209.940000    63.940000
max    9994.000000  99301.000000  ...  22638.480000  3773.080000

[8 rows x 8 columns]

Step 8: Display the Column Names

In [0]:
# Create price column
df["price"] = df["Sales"] / df["Quantity"]

# Create total_amount column
df["total_amount"] = df["price"] * df["Quantity"]

# Display the new columns
df[["Sales", "Quantity", "price", "total_amount"]].head()

      Sales  Quantity     price  total_amount
0  261.9600         2  130.9800      261.9600
1  731.9400         3  243.9800      731.9400
2   14.6200         2    7.3100       14.6200
3  957.5775         5  191.5155      957.5775
4   22.3680         2   11.1840       22.3680

Step 9: Display the Data Types

In [0]:
df.dtypes

Row ID             int64
Order ID          object
Order Date        object
Ship Date         object
Ship Mode         object
Customer ID       object
Customer Name     object
Segment           object
Country           object
City              object
State             object
Postal Code        int64
Region            object
Product ID        object
Category          object
Sub-Category      object
Product Name      object
Sales            float64
Quantity           int64
Discount         float64
Profit           float64
dtype: object

Step 10: Display Dataset Information

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

Step 11: Identify Missing Values

In [0]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Step 12: Handle Missing Values

In [0]:
df.fillna(method="ffill", inplace=True)

/home/spark-af355697-f0db-47e3-afe8-1d/.ipykernel/326/command-4557907890510258-173857299:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", inplace=True)

Step 13: Filter Rows

In [0]:
technology = df[df["Category"] == "Technology"]

technology.head()

    Row ID        Order ID  Order Date  ... Quantity Discount    Profit
7        8  CA-2014-115812  2014-06-09  ...        6      0.2   90.7152
11      12  CA-2014-115812  2014-06-09  ...        4      0.2   68.3568
19      20  CA-2014-143336  2014-08-27  ...        3      0.2   16.0110
26      27  CA-2016-121755  2016-01-16  ...        3      0.0   11.7741
35      36  CA-2016-117590  2016-12-08  ...        7      0.2  123.4737

[5 rows x 21 columns]

Step 14: Select Specific Columns

In [0]:
selected = df[["Order ID", "Customer Name", "Sales", "Quantity"]]

selected.head()

         Order ID    Customer Name     Sales  Quantity
0  CA-2016-152156      Claire Gute  261.9600         2
1  CA-2016-152156      Claire Gute  731.9400         3
2  CA-2016-138688  Darrin Van Huff   14.6200         2
3  US-2015-108966   Sean O'Donnell  957.5775         5
4  US-2015-108966   Sean O'Donnell   22.3680         2

Step 15: Remove Duplicate Rows

In [0]:
df.duplicated().sum()

np.int64(0)

In [0]:
df.drop_duplicates(inplace=True)

Step 16: Create a Derived Column

In [0]:
df["total_amount"] = df["Sales"] * df["Quantity"]

In [0]:
df[["Sales", "Quantity", "total_amount"]].head()

      Sales  Quantity  total_amount
0  261.9600         2      523.9200
1  731.9400         3     2195.8200
2   14.6200         2       29.2400
3  957.5775         5     4787.8875
4   22.3680         2       44.7360

In [0]:
df["price"] = df["Sales"] / df["Quantity"]
df["total_amount"] = df["price"] * df["Quantity"]

Step 17: Save the Cleaned Dataset

In [0]:
df.to_csv("/Workspace/Users/rohitkokare2324_it@sanjivanicoe.org.in/Cleaned_Superstore.csv", index=False)

 Step 18:Brief Summary

## Summary

- Loaded the Sample Superstore dataset.
- Explored the data using head(), tail(), shape, columns, dtypes, info(), and describe().
- Identified and handled missing values.
- Filtered rows and selected required columns.
- Removed duplicate records.
- Created the derived column total_amount.
- Saved the cleaned dataset as Cleaned_Superstore.csv.